[0m12:11:41.486641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BC1E4D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BE0D5460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BEAF3A40>]}


============================== 12:11:41.494619 | 3d4e6f82-e3cc-48b0-87ea-cd77403458b0 ==============================
[0m12:11:41.494619 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:11:41.495617 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init pjt_dbt', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:11:41.547479 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/hp/.dbt')}
[0m12:11:41.548475 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:11:41.554460 [debug] [MainThread]: Starter project path: C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m12:11:41.596874 [info ] [MainThread]: 
Your new dbt project "pjt_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:11:41.599867 [info ] [MainThread]: Setting up your profile.
[0m12:13:51.931462 [info ] [MainThread]: Profile pjt_dbt written to C:\Users\hp\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:13:51.933569 [debug] [MainThread]: Command `dbt init` succeeded at 12:13:51.933569 after 130.60 seconds
[0m12:13:51.942432 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BC1E4D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BEE7C0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218BF033F50>]}
[0m12:13:51.943430 [debug] [MainThread]: Flushing usage events
[0m12:13:53.025391 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:05:10.725753 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B778B5DD60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B7789917C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B7762CDBE0>]}


============================== 18:05:10.731703 | 5e0f9d68-3bcf-4419-a1e3-0e285d3b9091 ==============================
[0m18:05:10.731703 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:05:10.733698 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:05:10.734697 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Modern Data Stack\demo_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:05:10.735692 [debug] [MainThread]: Command `dbt run` failed at 18:05:10.735692 after 0.23 seconds
[0m18:05:10.736690 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B77866E8A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B779022570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B778B5DD60>]}
[0m18:05:10.736690 [debug] [MainThread]: Flushing usage events
[0m18:05:11.882662 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:07:39.993283 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252E5F25D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252EBC52B70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252EBC50B00>]}


============================== 18:07:39.998267 | 6dc04040-3eea-41f2-a9d7-314415ff7bf1 ==============================
[0m18:07:39.998267 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:07:40.000261 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:07:40.001261 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Modern Data Stack\demo_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:07:40.003255 [debug] [MainThread]: Command `dbt run` failed at 18:07:40.003255 after 0.20 seconds
[0m18:07:40.004253 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252EBAAE780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252E5F25D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252EBC537D0>]}
[0m18:07:40.005250 [debug] [MainThread]: Flushing usage events
[0m18:07:41.090884 [debug] [MainThread]: An error was encountered while trying to flush usage events
